### ISSUE TITLE
[DISCUSSION] Async support for CiscoSparkApi

### ISSUE THREAD

**Issue by tonybaloney** [CiscoDevNet/ciscosparkapi#33]
I put together a quick PoC of an async bot for Python and Cisco Spark.

https://github.com/tonybaloney/cisco-spark-async-bot

Happy to contribute this upstream, for bots async support get's really important when looking at multiple rooms, chats and discussions. Also, being able to use async callbacks is the difference between a fast bot and a sloow one :)

Thoughts? Does this go in another package? Would it be better to have seperate functions or a method wrapper, so that it can keep backward compat for non-Python 3 people.

**Comment by cmlccie** [comment]
Hi @tonybaloney !

Sorry for the delayed response.  This certainly is an interesting discussion.

Note that Spark bot architectures are usually constructed by creating [webhooks](https://developer.ciscospark.com/webhooks-explained.html) and responding to messages as webhook callbacks are received by your bot/app code rather than polling for messages.

How would you foresee this package working for you in an asynchronous program execution?  Could you provide some pseudocode with a use case that you are looking for?
