### ISSUE TITLE
webhooks.list() returning generator is not intuitive

### ISSUE THREAD

**Issue by kecorbin** [CiscoDevNet/ciscosparkapi#34]
From a user standpoint, I would actually expect a list, not generator here. 

https://github.com/CiscoDevNet/ciscosparkapi/blob/master/ciscosparkapi/api/webhooks.py#L124

**Comment by cmlccie** [comment]
Understood.  I was admittedly conflicted when designing package's API structure.

I decided to name all of the properties and methods using the same naming convention that the Cisco Spark documentation and parallel JavaScript SDKs use.  Which, when requesting a 'list' of items (be that rooms, messages, memberships, etc.), the Spark docks and SDKs use the term 'list'.

Due to calling the method 'list', one could certainly expect a Python list to be returned; however, a Python list would have to be retrieved all at once (to be an accurate / correct / complete response to the request).  This would require retrieving all results, requesting multiple pages of responses as needed, which ultimately might not be needed if the message, room, membership or etc. that you were looking for is in the first _n_ returned items.  Generators are much more efficient for this purpose, and save the package user a lot of time and headache, and if you actually really do want a Python list, you can easily create one from any generator using the list constructor `list(generator)`.

Still to your point... The method is called 'list' (to be consistent with the docs and SDKs) and returns a generator (which might not be expected and could cause some people grief).

I have considered a few enhancements to minimize any coding issues this terms issue might cause, I could enhance the `GeneratorContainer` class to provide the following list-like capabilities (which might help close the functionality gap in use):

* Add slicing support
* Add support for common methods like `len()`
* ...others

This would make the generator containers behave more like Python lists; however, there are notable (often positive but sometimes negative) outcomes...  Like:

* Everytime you call one of those `len()` like functions... A full list must be produced - imagine running this on messages for a long-standing highly-active Spark room.
* The data is always live!  When iterating the contents, you are always seeing the latest data from the cloud (normally a great thing)!  Except when you aren't expecting the contents of list to change, like indexing an item in the list (it was at index `2` and now it is at index `5`).
* If you really do want to iterate through the same static (and potentially stale) list of items... A list really is better.  ...and with the current design, you can always create one:  `list(generator)`

**Comment by cmlccie** [comment]
Note that this functionality is documented in the package documentation.

Check out:
[Working with Returned ‘Lists’ of Objects](http://ciscosparkapi.readthedocs.io/en/latest/user/quickstart.html#working-with-returned-lists-of-objects)

**Comment by kecorbin** [comment]
Thx
