### ISSUE TITLE
Would this repo remain the same with Webex Teams?

### ISSUE THREAD

**Issue by gaurcs** [CiscoDevNet/ciscosparkapi#60]
Since the official developer [page](https://developer.webex.com/sdks-and-widgets.html) for Cisco Webex doesn't have the SDK for Python, this repo is the de facto. Would the recent change of Cisco Spark to Webex Teams change anything here?

**Comment by cmlccie** [comment]
Hi @gaurcs , yes, yes it will.  😎  My time to work on this package has been a little sparse recently with other work commitments and taking some PTO with my newest little one (baby). 🙂  ...but I have started the work to match the Cisco Spark to Webex Teams changes in the [webexteamsdk](https://github.com/CiscoDevNet/ciscosparkapi/tree/webexteamsdk) branch.

Since the naming changes will be UX breaking changes (meaning you will have to update your code to use the new names of things), I am taking the opportunity to do a few things:

1. Introduce a few small breaking changes (like making the Webex Teams data object's date-time references actual Python datetime data types).
2. Merge in the work that was done on the `ciscosparksdk` project (some good work was done, but we never got the project off the ground).
3. Revamp the docs with updated references, structure, and (hopefully) a friendlier and more complete set of contributor docs.

# My plan is to:
1. Do the above work in the `webexteamsdk` branch.
2. Prepare the `webexteamsdk` package for release.
3. Rebrand this repo to now contain the `webexteamsdk` code, and move the `ciscosparkapi` code into it's own branch (for maintenance purposes).
4. Release a v1+ version of the new/updated `webexteamsdk` package and keep the `ciscosparkapi` package available for maintenance updates (as needed for some period of time ~ maybe a year or so).
5. Incorporate new features into `webexteamsdk` going forward.

**Comment by gaurcs** [comment]
Gotcha!Thanks for the detailed reply. And many many congrats on the baby!
